services:
  app:
    build: .
    ports:
      - "5173:5173"
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./scytalio.db
      - VITE_API_BASE_URL=http://localhost:8000
      - HOST=0.0.0.0
    volumes:
      - ./data:/app/data
    restart: unless-stopped