version: '3.8'

services:
  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./scytalio.db

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000

