services:
  app:
    build: .
    ports:
      - "5173:5173"
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/dbname
      - VITE_API_BASE_URL=http://localhost:8000
      - HOST=0.0.0.0
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
