version: '3.8'

services:
  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./scytalio.db
    volumes:
      - backend_data:/app/data

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    volumes:
      - frontend_node_modules:/frontend/node_modules

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend

volumes:
  backend_data:
  frontend_node_modules:
