name: Scytalio Build

permissions:
  contents: read
  issues: write
  pull-requests: write

on:
  push:
    branches: [ "staging", "main" ]
  pull_request:
    branches: [ "staging", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        pip install pytest-cov

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/app" >> $GITHUB_ENV

    - name: Run Tests with Coverage
      run: |
        pytest app/tests --cov=app --cov-report=xml
